---
kubernetes:
  children:
    master:
      hosts:
        k8s-01:
          ansible_host: 192.168.76.31
    worker:
      hosts:
        k8s-02:
          ansible_host: 192.168.76.32
        k8s-03:
          ansible_host: 192.168.76.33
