---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  METALLB_LB_RANGE: "192.168.76.12-192.168.76.21"
  METALLB_K8S_GATEWAY_ADDR: "192.168.76.12"
  METALLB_INGRESS_ADDR: "192.168.76.13"
  KUBE_VIP_ADDR: "192.168.76.22"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
